#!/usr/bin/env python

import os
import sys

vsc_config_dir = sys.path[0]
project_dir = vsc_config_dir.strip(".vscode")[:-1]

cmd = "sed -i 's#%s#%s#g' %s/c_cpp_properties.json" % (project_dir, "${workspaceFolder}", vsc_config_dir)
os.system(cmd)