xterm*locale: true
xterm.utf8: true
xterm*utf8Title: true

! 滚动条
XTerm*scrollBar: true
! XTerm*rightScrollBar: true
XTerm*SaveLines: 4096

! 颜色
! XTerm*background: black
! XTerm*foreground: green

! 复制粘贴
XTerm*VT100.translations: #override <Btn1Up>: select-end(PRIMARY, CLIPBOARD, CUT_BUFFER0)

! 查看本机上安装的字体使用fc-list
! 英文字体
xterm*faceName: DejaVu Sans Mono:antialias=True:pixelsize=13
! 中文字体
xterm*faceNameDoublesize:WenQuanYi Zen Hei Mono:antialias=True:pixelsize=13

! 输入法
XTerm*inputMethod:fcitx