local bg = "#282c34"

return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    opts = {
      caching = false,
      styles = {
        types = "NONE",
        methods = "NONE",
        numbers = "NONE",
        strings = "NONE",
        comments = "italic",
        keywords = "bold,italic",
        constants = "NONE",
        functions = "NONE",
        operators = "NONE",
        variables = "NONE",
        parameters = "NONE",
        conditionals = "italic",
        virtual_text = "NONE",
      },
      options = {
        cursorline = true,
        transparency = false,
        terminal_colors = true,
        highlight_inactive_windows = false,
      },
      highlights = {
        Normal = { bg = bg, fg = "#abb2bf" },
        NormalNC = { bg = bg, fg = "#abb2bf" },
        SignColumn = { bg = bg },
        SignColumnNC = { bg = bg },
        LineNr = { bg = bg, fg = "#495162" },
        LineNrNC = { bg = bg, fg = "#495162" },
        CursorLineNr = { bg = bg, fg = "#abb2bf" },
        CursorLineNrNC = { bg = bg, fg = "#495162" },
        CursorLine = { bg = "#2d313b" },
        CursorLineNC = { bg = bg },
        FoldColumn = { bg = bg, fg = "#495162" },
        FoldColumnNC = { bg = bg, fg = "#495162" },
        Folded = { bg = bg, fg = "#5c6370" },
        FoldedNC = { bg = bg, fg = "#5c6370" },
        WinBar = { bg = bg, fg = "#abb2bf" },
        WinBarNC = { bg = bg, fg = "#abb2bf" },
        WinSeparator = { bg = bg, fg = "#3e4452" },
        VertSplit = { bg = bg, fg = "#3e4452" },
        StatusLine = { bg = bg, fg = "#abb2bf" },
        StatusLineNC = { bg = bg, fg = "#abb2bf" },
        EndOfBuffer = { bg = bg, fg = bg },
        NeoTreeNormal = { bg = bg, fg = "#abb2bf" },
        NeoTreeNormalNC = { bg = bg, fg = "#abb2bf" },
        NeoTreeWinSeparator = { bg = bg, fg = "#3e4452" },
        NeoTreeVertSplit = { bg = bg, fg = "#3e4452" },
        EdgyNormal = { bg = bg },
        EdgyWinBar = { bg = bg },
        UserTerminalNormal = { bg = bg, fg = "#abb2bf" },
        TermCursor = { bg = "#abb2bf", fg = "#1e222a" },
        TermCursorNC = { bg = "#5c6370", fg = "#1e222a" },
      },
    },
  },
  {
    "AstroNvim/astroui",
    opts = {
      colorscheme = "onedark",
    },
  },
}
