[project]
name = "detect"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "omegaconf>=2.3.0",
    "robyn>=0.69.0",
    "ultralytics>=8.3.157",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
