for file in split(glob("~/.vim/init-scripts/*.vim"), '\n')
    exe 'source' file
endfor


for file in split(glob("~/.vim/custom/plugin-setting/*.vim"), '\n')
    exe 'source' file
endfor


for file in split(glob("~/.vim/custom/custom-setting/*.vim"), '\n')
    exe 'source' file
endfor
