#!/usr/bin/env python

import os

vsc_config_dir = os.path.dirname(os.path.abspath(__file__))
config_dir_suffix_name = os.path.basename(vsc_config_dir)

project_dir = vsc_config_dir
if config_dir_suffix_name != ".vscode":
    print("不在 .vscode 目录，现在退出")
    exit()

project_dir = vsc_config_dir.strip(".vscode")[:-1]

cmd = "sed -i 's#%s#%s#g' %s/c_cpp_properties.json" % (
    project_dir,
    "${workspaceFolder}",
    vsc_config_dir,
)

os.system(cmd)