set -g mouse on

# window 操作前缀
unbind C-b
set -g prefix C-w
bind C-w send-prefix

# window 的索引号
set -g base-index 1
set -g renumber-windows on

# 重命名 window
bind r command-prompt "rename-window '%%'"
bind x kill-window

# 当前 window 背景色
set -g window-status-current-style fg=white,bg=colour27,bold

# alt + 数字
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# alt + 左右
bind -n M-Left  previous-window
bind -n M-Right next-window

# Ctrl + 左右移动窗口顺序
bind -n C-Left swap-window -t -1
bind -n C-Right swap-window -t +1

# panel 操作前缀
bind -T root C-p switch-client -T pane-table
setw -g pane-base-index 1

# 根据支持情况加载变量
# 显示右侧的滚动条
if-shell -b 'tmux set -g pane-scrollbars on 2>/dev/null' {
    set -g pane-scrollbars on
    set -g pane-scrollbars-position right
}

# 面板操作键表
set -g pane-border-status top
bind -T pane-table h split-window -h -c "#{pane_current_path}"
bind -T pane-table v split-window -v -c "#{pane_current_path}"
bind -T pane-table o select-pane -t :.+
bind -T pane-table i select-pane -t :.-
bind -T pane-table x kill-pane
bind -T pane-table Space select-layout even-horizontal
bind -T pane-table Enter select-layout even-vertical

# ctrl-p r：重命名当前 pane
bind -T pane-table r command-prompt -I "#T" "select-pane -T '%%'"


# 复制粘贴
setw -g mode-keys vi
set -g set-clipboard on

# 终端模拟器不支持 OSC52 的时候用
# ssh -YC 复制到本地剪贴板
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# 粘贴：Ctrl+Shift+V
bind -n C-S-v paste-buffer


# 右下角
set -g status-interval 60
set -g status-right ' #(date "+%Y-%m-%d %H:%M") '
set -g status-right-style fg=white,bg=colour27,bold