source ~/.zinit/bin/zinit.zsh
source ~/.local/etc/profile
source ~/.profile

# 插件
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting
zinit light zsh-users/zsh-completions

# 设置补全
autoload -U compinit && compinit

# 主题
zinit snippet OMZT::steeef
